name: Build debug image with vcpkg caching

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DOCKER_BUILD_SUMMARY: false
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha
          type=raw,value=debug
    
    # Restore cache from previous runs
    - name: Use cache for vcpkg
      id: cache
      uses: actions/cache@v4
      with:
        path: vcpkg-cache
        key: vcpkg-${{ runner.os }}-debug-v0.6-${{ hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-debug-v0.6-

    - name: Inject vcpkg-cache
      uses: reproducible-containers/buildkit-cache-dance@v2.1.4
      with:
        cache-source: vcpkg-cache
        cache-target: /vcpkg-cache
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
        
    
    # Build Docker image with vcpkg cache mounted
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max